@startuml
title "Calc Depth flow-process diagram"

(*) --> "Init Device()"
-->"ObcInitWithFile()"

-->"WaitforFrameGroup()"
-->"ObcFrameGroupUnpackMipi()"
-->"ObcGetMiddleFrameGroup()"

if "is not hasFrameInDepthLib() or hasLoseFrame?" then
    -->[yes] "ObcCalcDepth(kUseFrameBoth)"
    -->"GetDepthFrameDoSth()"
    -->"WaitforFrameGroup()"
else
    -->[no] "ObcCalcDepth(kUseFrame0)"
    -->"GetDepthFrameDoSth0()"
    -->"ObcCalcDepth(kUseFrame1)"
    -->"GetDepthFrameDoSth1()"
    -->"WaitforFrameGroup()"
endif



@enduml
