@startuml

skinparam backfroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {

    ArrowColor DeepSkyBlue
    ActorBorderColor blue
    LifeLineBorderColor blue
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor DeepSkyBlue
    ParticipantBackgroundColor DodgerBlue
    ParticipantFontName Aapex
    ParticipantFontColor #A9DCDF

    ActorBackgroundColor aqua
    ActorFontColor DeepSkyBlue
    ActorFontSize 17
    ActorFontName Aapex
}
App->OpenNI_Device:"open()"
OpenNI_Device->ONI_C_API:"oniDeviceOpen()"
ONI_C_API ->ONI_C_API:"oniDeviceOpenEx()"
ONI_C_API->g_Context:"deviceOpen()"
g_Context->XnOniDriver:"m_driverHandler.deviceOpen()"
XnOniDriver->XnOniDevice:"Init()"
XnOniDevice->XnSensor:"Init(&config)"
XnSensor->XnSensor:"InitImpl(pDeviceConfig)"
XnSensor->XnSensor:"xnSchedulerStart(&m_pScheduler)"
XnSensor->XnSensor:"InitSensor()"
XnSensor->m_SensorIO:"OpenDevice(pDeviceConfig->cpConnectionString)"
m_SensorIO->Xnlib:"xnUSBOpenDeviceByPath()"
m_SensorIO->Xnlib:"xnUSBOpenEndPoint()"
XnSensor->m_SensorIO:""

@enduml