@startuml

skinparam backfroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {

    ArrowColor DeepSkyBlue
    ActorBorderColor blue
    LifeLineBorderColor blue
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor DeepSkyBlue
    ParticipantBackgroundColor DodgerBlue
    ParticipantFontName Aapex
    ParticipantFontColor #A9DCDF

    ActorBackgroundColor aqua
    ActorFontColor DeepSkyBlue
    ActorFontSize 17
    ActorFontName Aapex
}

openni->ONI_C_API:"oniInitialize()" 
ONI_C_API->Context:"initialize()"
Context->Context:"resolvePathToOpenNI()"
Context->Context:"configure()"

loop "Context->loadLibraries()遍历驱动dll"
Context->XnOniDriver:"initialize()"
XnOniDriver->XnDeviceEnumeration:"Initialize()"
XnDeviceEnumeration->Xnlib:"xnUSBInit()"
Xnlib->Xnlib:"xnUSBPlatformSpecificInit()"
Xnlib->Xnlib:"xnOSCreateThread(DevDetectThread)"
XnDeviceEnumeration->Xnlib:"check products in ms_supportedProducts"
end




@enduml