@startuml

skinparam backfroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {

    ArrowColor DeepSkyBlue
    ActorBorderColor blue
    LifeLineBorderColor blue
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor DeepSkyBlue
    ParticipantBackgroundColor DodgerBlue
    ParticipantFontName Aapex
    ParticipantFontColor #A9DCDF

    ActorBackgroundColor aqua
    ActorFontColor DeepSkyBlue
    ActorFontSize 17
    ActorFontName Aapex
}

张三 -> 李四 : 我要借钱
activate 张三
activate 李四

李四 -> 李四 : 四处筹钱
activate 李四 #FFBBBB

李四 -> 王五 : 你给他担保我才借
activate 王五

王五 --> 李四 : 我给他担保 
destroy 王五

deactivate 李四

李四 --> 张三 : 借给你

张三 -> 李四 : 我要还钱
李四 --> 张三 : 收到欠款
deactivate 李四

张三 -> 李四 : 我还要借钱
李四 --> 张三 : 不借了
deactivate 张三

@enduml